name: dbtdemo
version: 1.0.0

config-version: 2

# Define your profiles.yml configuration to connect to Databricks
profile: dbtdbx

target-path: "target"

# Specify where dbt should look for models
model-paths: ["dbtdemo/models"]

# Data models configurations
models:
  basic_model:
          +materialized: table
          +schema: default

vars:
  databricks_catalog: dbtdbx_data

# Define which environments this project can run on
require-dbt-version: [">=1.0.0"]
