name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'databricks'  # Update this to match your profile configuration

# Paths for files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model Configuration
models:
  my_new_project:
    example:
      +materialized: table  # Applies to models in models/example
    +materialized: table    # Applies to all models, including those outside 'example'
