name: dbtdemo
version: 1.0.0
config-version: 2

profile: dbtdbx

# Simple model paths configuration
model-paths: ["models"]

# Make sure this matches exactly
models:
  dbtdemo:
    +schema: default
    +materialized: table

vars:
  databricks_catalog: dbtdbx_data

require-dbt-version: [">=1.0.0"]