name: dbtdemo
version: 1.0.0
config-version: 2

profile: dbtdbx

target-path: "target"

# Update this - just point to the models directory
model-paths: ["models"]

models:
  dbtdemo:
    # Default configurations for all models
    +materialized: table
    +schema: default

vars:
  databricks_catalog: dbtdbx_data

require-dbt-version: [">=1.0.0"]
